FROM rust:slim-bullseye AS planner

WORKDIR /app

RUN cargo install cargo-chef

COPY . .

RUN cargo chef prepare --recipe-path recipe.json

FROM rust:slim-bullseye AS builder

WORKDIR /app

RUN cargo install cargo-chef

COPY --from=planner /app/recipe.json recipe.json

RUN cargo chef cook --release --recipe-path recipe.json

COPY . .

RUN cargo build --release

FROM debian:bullseye-slim

COPY --from=builder /app/target/release/rust /usr/local/bin/rust

ENTRYPOINT ["rust"]
